development:
  user: 'ic'
  password: 'ic'
  host: 200.143.198.46
  port: 9885
  callback_url: 'http://google.com.br/conteudos/granularizou'
  callback_verb: 'GET'

test:
  user: 'ic'
  password: 'ic'
  host: 200.143.198.46
  port: 9885
  callback_url: 'http://google.com.br/conteudos/granularizou'
  callback_verb: 'GET'

production:
  user:
  password:
  port: