development:
  user: 'test'
  password: 'test'
  host: 10.12.0.207
  port: 8885
  callback_url: 'http://10.12.4.32:3000/conteudos/granularizou'
  callback_verb: 'POST'

test:
  user: 'test'
  password: 'test'
  host: 10.12.0.207
  port: 8885
  callback_url: 'http://10.12.4.32:3000/conteudos/granularizou'
  callback_verb: 'POST'

production:
  user:
  password:
  port: