development:
  user: 'test'
  password: 'test'
  host: localhost
  port: 8885
  callback_url: 'http://localhost:3000/conteudos/granularizou'
  callback_verb: 'POST'

test:
  user: 'test'
  password: 'test'
  host: localhost
  port: 8885
  callback_url: 'http://localhost:3000/conteudos/granularizou'
  callback_verb: 'POST'

production:
  user:
  password:
  port: